### ISSUE TITLE
terraform bundle cannot find the release

### ISSUE THREAD

**Issue by mikecook** [terraform-providers/terraform-provider-aviatrix#7]
```Failed to resolve aviatrix provider ~> 2.1.29: no provider exists with the given name```

Can you make sure it gets added or updated?

**Comment by cgriggs01** [comment]
Hi @mikecook,

There are a few final changes to be made before we can build the first release that will be available through Terraform init.

**Comment by cgriggs01** [comment]
Hi @mikecook,

We're working to get the providers first released to releases.hashicorp.com, there were just some last minute documentation chances and then we will publish a 2.2.0 version of the provider that will be accessible through `terraform init`.

**Comment by mikecook** [comment]
`v2.2.0` works. Thank you. Closing.
